name: Delete old build branches
description: Delete old build branches
author: Osman Faruk Bayram

branding:
  icon: trash-2
  color: yellow

input:
  github_token:
    description: "The github token to use on requests to the github api"
    required: true

output:
  deleted_branches:
    description: "The list of branches that has been deleted"

runs:
  using: docker
  image: 'Dockerfile'
  args:
    - ${{ inputs.github_token }}